# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22bf1e32193ff40fba5c9b484db8db03f380313d5927c9d0ea84c1ba22980eef7dcb13e6d8c515aaee35231742b54d4702fcde98ba5921c2f60c318b00b2b643

test:
  secret_key_base: 498b4058049a3ce215e23e880f3001be0e41eefd7efd7c1068a8a9a9fbcdcef521bd9db24249929365c63484be3bd3c50e3522c055609aab3590ef792f8f2448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
